# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CLIR 60th Anniversary
email: ""
description: > # Metadata description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://60.clir.org/" # the base hostname & protocol for your site
twitter_username: clirnews
github_username:  clirdlf

google-tracking-id: ""

exclude: ['.gitignore', '.env', '.git', 'node_modules']
sass:
  style: compressed

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-feed

